### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by CodeOcenS** [below/MatterSample#2]
After I modify the bundle ID, the project cannot be compiled. If I want to successfully use MatterSupport, do I have to apply for `com.apple.developer.networking.manage-thread-network-credentials`? At present, I keep prompting the following error after scanning the code
`Error Domain=HMFErrorDomain Code=12 "Operation canceled." UserInfo={NSLocalizedDescription=Operation canceled.}`
 or 
`Error Domain=HMErrorDomain Code=18 "Pairing Failed" UserInfo={NSLocalizedDescription=Pairing Failed, NSUnderlyingError=0x280adfe40 {Error Domain=HAPErrorDomain Code=15 "(null)"}}`

**Comment by below** [comment]
Yes, for the sample to work like this you need `com.apple.developer.networking.manage-thread-network-credentials`. That said, this applies only for the Thead part. The MatterSupport Framework should work without this entitlement

**Comment by CodeOcenS** [comment]
We don't plan to use Thread, I try to delete `com.apple.developer.networking.manage-thread-network-credentials`, the project can compile and run. But still got error:
`Error Domain=HMFErrorDomain Code=12 "Operation canceled." UserInfo={NSLocalizedDescription=Operation canceled.}`
Is it related to the mobile phone system? I tried both from iOS16.1-iOS16.2, based on this error. But the actual device has been configured into the network.

**Comment by below** [comment]
You are seeing the precise error I see. The project is meant to demonstrate that issue

**Comment by GollenGao** [comment]
You can try to use the App Groups to save the  onboardingPayload
`
   override func commissionDevice(in home: MatterAddDeviceRequest.Home?, onboardingPayload: String, commissioningID: UUID) async throws {
        let userDefault = UserDefaults(suiteName: "")
        userDefault?.set(onboardingPayload, forKey: "")
    }
`
Then，In your APP get it.

**Comment by CodeOcenS** [comment]
> You can try to use the App Groups to save the onboardingPayload `override func commissionDevice(in home: MatterAddDeviceRequest.Home?, onboardingPayload: String, commissioningID: UUID) async throws { let userDefault = UserDefaults(suiteName: "") userDefault?.set(onboardingPayload, forKey: "") }` Then，In your APP get it.

Thanks! I will try it.
