### ISSUE TITLE
Matter Sample Not Work 

### ISSUE THREAD

**Issue by HururuekChapChap** [below/MatterSample#3]
Really thank you for making MatterSupport Sample Code.

I removed "com.apple.developer.networking.manage-thread-network-credentials" and the build succeeded.

However, when I click the "Add Device with Barcode" button, the MatterAddDeviceRequest.perform is executed,
but Apple Register UI is no response.

Do I need to register "com.apple.developer.networking.manage-thread-network-credentials" for use MatterSupport.framework if I don't want to use Thread?

Or is it possible to register as a Wifi("Add Device with Barcode") after registering a "com.apple.developer.networking.multicast"?
[link](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast)

How can I register as a MatterSupport.Framework?

**Device State**

![IMG_79EE02335045-1](https://user-images.githubusercontent.com/57618897/216030571-53754428-4b95-4967-b805-d6c9b3259947.jpeg)

**M5 Stack Log**

<img width="861" alt="image" src="https://user-images.githubusercontent.com/57618897/216030727-346dace9-85e8-4e7b-a6e7-84d4cdec6dd8.png">

**Comment by below** [comment]
> Really thank you for making MatterSupport Sample Code.

You are welcome!

> Do I need to register "com.apple.developer.networking.manage-thread-network-credentials" for use MatterSupport.framework if I don't want to use Thread?

No, you should not need that

Remember, this sample is provided because I can't get it to work either. I will update it as soon as I know more

**Comment by HururuekChapChap** [comment]
Thank you for fasted response.

In the 16.3 version, registration works well.
Do you know how to call MatterAddDeviceExtensionRequestHandler?

I thought the MatterAddDeviceExtensionRequestHandler would be called after the MatterAddDeviceRequest.perform().
